---
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nwdb-deploy
  namespace: nwns
  labels:
    name: nwdb
    version: v1

spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: nwdb
      version: v1
  template: 
    metadata: 
      name: nwdb-pod
      labels: 
        name: nwdb
        version: v1

    spec: 
      containers: 
      - name: nwdb-container
        image: geekwannabe555/nw_db:0.0.1
        imagePullPolicy: IfNotPresent
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: nwapp-secret
              key: db_password
        ports: 
        - name: nwdb-port
          containerPort: 3306

---
apiVersion: v1
kind: Service

metadata: 
  name: nwdb-svc
  namespace: nwns
  labels: 
    name: nwdb-svc
    version: v1

spec:
  type: ClusterIP
  selector:
    name: nwdb
    version: v1
  ports: 
  - name: http
    port: 3306
    targetPort: nwdb-port
