---
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nwserver-deploy
  namespace: nwns
  labels:
    name: nwserver
    version: v1

spec: 
  replicas: 3
  selector: 
    matchLabels:
      name: nwserver
      version: v1
  template: 
    metadata: 
      name: nwserver-pod
      labels: 
        name: nwserver
        version: v1

    spec: 
      containers: 
      - name: nwserver-container
        image: greenandwhite/nwserver
        imagePullPolicy: IfNotPresent
        env: 
        - name: DB_HOST
          value: nwdb-svc
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: nwapp-secret
              key: db_password
        - name: INSTANCE_IP_ADDRESS
          valueFrom: 
            fieldRef: 
              fieldPath: status.podIP
        ports: 
        - name: nwserver-port
          containerPort: 3000

---
apiVersion: v1
kind: Service

metadata: 
  name: nwserver-svc
  namespace: nwns
  labels: 
    name: nwserver-svc
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: nwserver
    version: v1
  ports: 
  - name: http
    port: 80
    targetPort: nwserver-port
