---
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nwserver-deploy
  namespace: nwns
  labels:
    name: nwserver
    version: v1

spec: 
  replicas: 3
  selector: 
    matchLabels:
      name: nwserver
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      name: nwserver-pod
      labels: 
        name: nwserver
        version: v1

    spec: 
      containers: 
      - name: nwserver-container
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        livenessProbe: 
          httpGet:
            path: /health
            port: nwserver-port
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env: 
        - name: DB_HOST
          value: nwdb-svc
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: nwapp-secret
              key: db_password
        - name: INSTANCE_IP_ADDRESS
          valueFrom: 
            fieldRef: 
              fieldPath: status.podIP
        ports: 
        - name: nwserver-port
          containerPort: 3000
